export const MAKERS_TEAM_URL =
  'https://makers.sopt.org/?utm_source=playground&utm_medium=footer&utm_campaign=recruiting&utm_id=3rd_makers';

export const playgroundLink = {
  memberList: () => `/members`,
  teamLeaderList: () => `/members/team-leaders`,
  memberDetail: (id: string | number) => `/members/${id}`,
  memberUpload: () => `/members/upload`,
  memberEdit: () => '/members/edit',
  memberCheckSoptActivity: () => '/members/checkSoptActivity',
  projectList: () => `/projects`,
  projectDetail: (id: string | number) => `/projects/${id}`,
  projectUpload: () => `/projects/upload`,
  projectEdit: (id: string | number) => `/projects/edit/${id}`,
  groupList: () => '/group',
  groupDetail: (id: string | number) => `/group/detail?id=${id}`,
  intro: () => `/intro`,
  login: () => `/accounts`,
  register: () => `/accounts/sign-up/auth`,
  resetLogin: () => `/auth/reset`,
  reconnectSocialAuth: () => `/auth/reconnect`,
  connectSocialAuth: () => `/auth/register`,
  makers: () => `/makers`,
  blog: () => `/blog`,
  blogSuccess: () => `/blog/success`,
  mentoringDetail: (id: number) => `/mentoring/${id}`,
  wordchain: () => `/wordchain`,
  feedList: () => `/`,
  feedDetail: (id: string | number) => `/feed/${id}`,
  feedUpload: () => `/feed/upload`,
  feedEdit: (id: string | number) => `/feed/edit/${id}`,
  remember: () => `/remember`,
  coffeechatUpload: () => `/coffeechat/upload`,
  coffeechatEdit: (id: string | number) => `/coffeechat/edit/${id}`,
  coffeechat: () => `/coffeechat`,
  coffeechatDetail: (id: string | number) => `/coffeechat/${id}`,
  mySoptReport: () => `/mySoptReport`,
  accounts: () => `/accounts`,
};

export const crewLink = {
  crewHome: () => `/group`,
  feedDetail: (id: string | number) => `/group/post?id=${id}`,
  groupDetail: (id: string | number) => `/group/detail?id=${id}`,
};
