export const ALL_CATEGORY_CODE = 'ALL';
export const SOPTICLE_CATEGORY_CODE = 'SOPTICLE';
export const FREE_CATEGORY_CODE = 'FREE';
export const PROMOTION_CATEGORY_CODE = 'PROMOTION';
export const ANONYMOUS_MEMBER_ID = -1;

export const MAIN_CATEGORY_CODE = [PROMOTION_CATEGORY_CODE, SOPTICLE_CATEGORY_CODE, FREE_CATEGORY_CODE];

export const SUB_CATEGORY_CODE: Record<string, string[]> = {
  [PROMOTION_CATEGORY_CODE]: ['RECRUIT', 'PROJECT', 'ETC', 'EVENT'],
  [SOPTICLE_CATEGORY_CODE]: ['PLAN', 'DESIGN', 'WEB', 'SERVER', 'IOS', 'ANDROID'],
};
