import type { CategorySelectType } from '@/components/feed/upload/Category/types';

export const categories: CategorySelectType = [
  {
    code: 'FREE',
    name: '자유',
    content: '자유롭게 다양한 이야기를 해요.',
    hasBlind: false,
    children: [],
  },
  {
    code: 'PART',
    name: '파트',
    content: '기획, 디자인, 서버, 웹, iOS, Android에 대한 이야기를 해요.',
    hasBlind: false,
    children: [
      {
        code: 'PART_PLAN',
        name: '기획',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PART_DESIGN',
        name: '디자인',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PART_SERVER',
        name: '서버',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PART_WEB',
        name: '웹',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PART_IOS',
        name: 'iOS',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PART_ANDROID',
        name: 'Android',
        content: null,
        hasBlind: false,
        children: [],
      },
    ],
  },
  {
    code: 'SOPT',
    name: 'SOPT 활동',
    content: '앱잼, 솝커톤, 솝텀을 포함해 다양한 SOPT에 대한 이야기를 해요.',
    hasBlind: false,
    children: [
      {
        code: 'SOPT_APPJAM',
        name: '앱잼',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'SOPT_SOPKATHON',
        name: '솝커톤',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'SOPT_SOPTERM',
        name: '솝텀',
        content: null,
        hasBlind: false,
        children: [],
      },
    ],
  },
  {
    code: 'PROMOTION',
    name: '홍보',
    content: '채용, 행사, 스터디, 설문조사 등 모든 홍보는 여기서 이야기 해요.',
    hasBlind: false,
    children: [
      {
        code: 'PROMOTION_RECRUIT',
        name: '모집',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PROMOTION_JOB',
        name: '채용',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PROMOTION_PROJECT',
        name: '프로젝트',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'PROMOTION_EVENT',
        name: '행사',
        content: null,
        hasBlind: false,
        children: [],
      },
    ],
  },
  {
    code: 'CAREER',
    name: '취업/진로',
    content: '취업, 진로에 대한 다양한 이야기를 해요.',
    hasBlind: false,
    children: [
      {
        code: 'CAREER_REVIEW',
        name: '후기',
        content: null,
        hasBlind: false,
        children: [],
      },
      {
        code: 'CAREER_TIP',
        name: '꿀팁',
        content: null,
        hasBlind: false,
        children: [],
      },
    ],
  },
];
