/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 2
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'default';

export const ApiKey: Record<Environment, string> = {
  default: '765c1919975291c332c4fd993d9b9a9d',
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '2',
    branch: 'main',
    source: 'web',
    versionId: '674c51fe-51fc-49eb-b0d4-b17a89c6340c',
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0',
    },
  },
};

export interface LoadOptionsBase {
  disabled?: boolean;
}

export type LoadOptionsWithEnvironment = LoadOptionsBase & {
  environment: Environment;
  client?: { configuration?: BrowserOptions };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface ApplyMultiplefilterProperties {
  /**
   * 유저의 활동 기수 선택 여부를 파악합니다.
   */
  'Applied_generation'?: boolean;
  /**
   * 유저가 선택한 대상 파트를 의미합니다.
   */
  'Applied_part'?: string;
  /**
   * 유저가 선택한 카테고리를 의미합니다.
   */
  'Applied-category'?: string;
  /**
   * 유저가 선택한 키워드를 의미합니다.
   */
  'Applied-keyword'?: string;
  /**
   * 유저가 선택한 모집 상태를 의미합니다.
   */
  'Applied-status'?: string;
}

export interface ApplySoptmapFilterProperties {
  /**
   * 솝맵에서 유저가 선택한 카테고리 필터값을 의미
   */
  soptmap_category: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface AttachFeedPhotoProperties {
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickBannerProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  banner_id?: number;
  banner_timestamp?: any;
  banner_url?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickCarouselArrowProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  image_total?: number;
}

export interface ClickCommentLikeProperties {
  crew_status?: boolean;
}

export interface ClickDraftDialogProperties {
  /**
   * 임시저장 다이얼로그가 노출되었을 때 사용자가 어떤 버튼을 선택했는지를 의미합니다.
   *
   * * \[새로 쓰기\] 버튼 클릭 시 **new**
   *
   * * \[이어서 쓰기\] 버튼 클릭 시 **resume**
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | new, resume |
   */
  dialog_action: 'new' | 'resume';
}

export interface ClickEventApplyProperties {
  /**
   * 유저의 활동 기수 선택 여부를 파악합니다.
   */
  Applied_generation?: boolean;
  /**
   * 유저가 클릭한 행사 cta버튼이 위치한 영역
   */
  event_cta_location?: string;
  /**
   * cta 버튼을 누른 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  event_id?: number;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickEventbannerMainCtaProperties {
  /**
   * cta 버튼을 누른 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  event_id?: number;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickEventbannerSubCtaProperties {
  /**
   * 클릭 대상 기수 상태
   */
  event_generation_type?: string;
  /**
   * cta 버튼을 누른 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  event_id?: number;
  location?: string;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickFeedCardProperties {
  crew_status?: boolean;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  feed_comment_total?: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  feed_id?: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  feed_image_total?: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  feed_like_total?: number;
  feed_title?: string;
  feed_upload?: any;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  location?: string;
  platform_type?: string;
}

export interface ClickFeedCardGroupLabelProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  location?: string;
}

export interface ClickFeeddetailLikeProperties {
  crew_status?: boolean;
}

export interface ClickFeeddetatilProfileProperties {
  crew_status?: boolean;
}

export interface ClickFeedlistLikeProperties {
  crew_status?: boolean;
  location?: string;
}

export interface ClickFeedPostingProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  location?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickFeedProfileProperties {
  crew_status?: boolean;
  location?: string;
}

export interface ClickFilterCategoryProperties {
  group_category?: string;
}

export interface ClickFilterGenerationProperties {
  group_generation?: boolean;
}

export interface ClickFilterPartProperties {
  group_part?: string;
}

export interface ClickFilterStatusProperties {
  group_status?: string;
}

export interface ClickGroupCardProperties {
  group_category?: string;
  group_generation?: boolean;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_owner_id?: number;
  group_part?: string;
  group_status?: string;
  group_title?: string;
}

export interface ClickMakeGroupProperties {
  location?: string;
}

export interface ClickMemberStatusProperties {
  crew_status?: boolean;
}

export interface ClickNavbarGroupProperties {
  menu?: string;
}

export interface ClickOwnerProfileProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_owner_id?: number;
}

export interface ClickPaginationArrowProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  page?: number;
}

export interface ClickPaginationNumberProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  page?: number;
}

export interface ClickRegisterGroupProperties {
  /**
   * 사용자가 네트워킹 행사 CTA를 통해 진입했는지 확인하기 위한 유입소스를 의미합니다.
   */
  entry_source?: string;
  /**
   * cta 버튼을 누른 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  event_id?: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  location?: string;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickSoptmapPromotionCheckGiftProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickSoptmapPromotionLoseConfirmProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickSoptmapPromotionWinCtaProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ClickSoptmapRecommendProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
}

export interface ClickViewMemberModalProperties {
  /**
   * 유저의 활동 기수 선택 여부를 파악합니다.
   */
  Applied_generation?: boolean;
  /**
   * 유저가 선택한 대상 파트를 의미합니다.
   */
  Applied_part?: string;
  /**
   * 사용자가 네트워킹 행사 CTA를 통해 진입했는지 확인하기 위한 유입소스를 의미합니다.
   */
  entry_source?: string;
  group_category?: string;
  group_generation?: boolean;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  group_id?: number;
  location?: string;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface CompleteSoptmapRegistrationProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
}

export interface CompletedCommentPostingProperties {
  crew_status?: boolean;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface CompletedFeedPostingProperties {
  feed_upload?: any;
  location?: string;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface CompletedFeedPostingCanceledProperties {
  location?: string;
  platform_type?: string;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface CompletedMakeGroupProperties {
  /**
   * 사용자가 ‘이어서 쓰기’를 통해 모임 개설하기 페이지에 진입했는지를 의미합니다.
   */
  from_resume: boolean;
}

export interface FilterListOptionManagementProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  manage_listing_no?: number;
}

export interface FilterManagementListOrderProperties {
  manage_sort?: string;
}

export interface ImpressionBannerProperties {
  /**
   * 배너 광고의 고유 ID 값을 의미합니다.
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  banner_id?: number;
  banner_timestamp?: any;
  banner_url?: string;
}

export interface PushEnteredUserProperties {
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface StartGroupProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  screen_width: number;
}

export interface ViewSoptmapFirstRegisterPromotionProperties {
  /**
   * 솝맵 장소 목록의 고유 ID 값을 의미
   *
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  place_id: number;
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export interface ViewSoptmapTabProperties {
  /**
   * 유저 아이디값
   *
   * | Rule | Value |
   * |---|---|
   * | Type | integer |
   */
  user_id?: number;
}

export class ApplyMultiplefilter implements BaseEvent {
  event_type = 'Apply-multiplefilter';

  constructor(public event_properties?: ApplyMultiplefilterProperties) {
    this.event_properties = event_properties;
  }
}

export class ApplySoptmapFilter implements BaseEvent {
  event_type = 'Apply-soptmapFilter';

  constructor(public event_properties: ApplySoptmapFilterProperties) {
    this.event_properties = event_properties;
  }
}

export class AttachFeedPhoto implements BaseEvent {
  event_type = 'Attach-feedPhoto';

  constructor(public event_properties?: AttachFeedPhotoProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickBanner implements BaseEvent {
  event_type = 'Click-banner';

  constructor(public event_properties?: ClickBannerProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickCarouselArrow implements BaseEvent {
  event_type = 'Click-carouselArrow';

  constructor(public event_properties?: ClickCarouselArrowProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickCommentLike implements BaseEvent {
  event_type = 'Click-commentLike';

  constructor(public event_properties?: ClickCommentLikeProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickDraftDialog implements BaseEvent {
  event_type = 'Click-draft-dialog';

  constructor(public event_properties: ClickDraftDialogProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickEventApply implements BaseEvent {
  event_type = 'Click-event-apply';

  constructor(public event_properties?: ClickEventApplyProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickEventbannerMainCta implements BaseEvent {
  event_type = 'Click-eventbanner-mainCTA';

  constructor(public event_properties?: ClickEventbannerMainCtaProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickEventbannerSubCta implements BaseEvent {
  event_type = 'Click-eventbanner-subCTA';

  constructor(public event_properties?: ClickEventbannerSubCtaProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedAction implements BaseEvent {
  event_type = 'Click-feedAction';
}

export class ClickFeedCard implements BaseEvent {
  event_type = 'Click-feedCard';

  constructor(public event_properties?: ClickFeedCardProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedCardGroupLabel implements BaseEvent {
  event_type = 'Click-feedCardGroupLabel';

  constructor(public event_properties?: ClickFeedCardGroupLabelProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeeddetailLike implements BaseEvent {
  event_type = 'Click-feeddetailLike';

  constructor(public event_properties?: ClickFeeddetailLikeProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeeddetatilProfile implements BaseEvent {
  event_type = 'Click-feeddetatilProfile';

  constructor(public event_properties?: ClickFeeddetatilProfileProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedlistLike implements BaseEvent {
  event_type = 'Click-feedlistLike';

  constructor(public event_properties?: ClickFeedlistLikeProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedPosting implements BaseEvent {
  event_type = 'Click-feedPosting';

  constructor(public event_properties?: ClickFeedPostingProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedProfile implements BaseEvent {
  event_type = 'Click-feedProfile';

  constructor(public event_properties?: ClickFeedProfileProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFeedShard implements BaseEvent {
  event_type = 'Click-feedShard';
}

export class ClickFilterCategory implements BaseEvent {
  event_type = 'Click-filterCategory';

  constructor(public event_properties?: ClickFilterCategoryProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFilterGeneration implements BaseEvent {
  event_type = 'Click-filterGeneration';

  constructor(public event_properties?: ClickFilterGenerationProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFilterOn implements BaseEvent {
  event_type = 'Click-filterOn';
}

export class ClickFilterPart implements BaseEvent {
  event_type = 'Click-filterPart';

  constructor(public event_properties?: ClickFilterPartProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickFilterStatus implements BaseEvent {
  event_type = 'Click-filterStatus';

  constructor(public event_properties?: ClickFilterStatusProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickGroupCard implements BaseEvent {
  event_type = 'Click-groupCard';

  constructor(public event_properties?: ClickGroupCardProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickMakebymeGroup implements BaseEvent {
  event_type = 'Click-makebymeGroup';
}

export class ClickMakeGroup implements BaseEvent {
  event_type = 'Click-makeGroup';

  constructor(public event_properties?: ClickMakeGroupProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickManageGroup implements BaseEvent {
  event_type = 'Click-manageGroup';
}

export class ClickManagementListProfile implements BaseEvent {
  event_type = 'Click-managementListProfile';
}

export class ClickMemberManagement implements BaseEvent {
  event_type = 'Click-memberManagement';
}

export class ClickMemberStatus implements BaseEvent {
  event_type = 'Click-memberStatus';

  constructor(public event_properties?: ClickMemberStatusProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickNavbarGroup implements BaseEvent {
  event_type = 'Click-navbarGroup';

  constructor(public event_properties?: ClickNavbarGroupProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickNoticeOff implements BaseEvent {
  event_type = 'Click-noticeOff';
}

export class ClickNoticeOn implements BaseEvent {
  event_type = 'Click-noticeOn';
}

export class ClickOwnerProfile implements BaseEvent {
  event_type = 'Click-ownerProfile';

  constructor(public event_properties?: ClickOwnerProfileProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickPaginationArrow implements BaseEvent {
  event_type = 'Click-paginationArrow';

  constructor(public event_properties?: ClickPaginationArrowProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickPaginationNumber implements BaseEvent {
  event_type = 'Click-paginationNumber';

  constructor(public event_properties?: ClickPaginationNumberProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickRegisteredGroup implements BaseEvent {
  event_type = 'Click-registeredGroup';
}

export class ClickRegisterGroup implements BaseEvent {
  event_type = 'Click-registerGroup';

  constructor(public event_properties?: ClickRegisterGroupProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickSoptmapPromotionCheckGift implements BaseEvent {
  event_type = 'Click-soptmapPromotionCheckGift';

  constructor(public event_properties: ClickSoptmapPromotionCheckGiftProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickSoptmapPromotionLoseConfirm implements BaseEvent {
  event_type = 'Click-soptmapPromotionLoseConfirm';

  constructor(public event_properties: ClickSoptmapPromotionLoseConfirmProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickSoptmapPromotionWinCta implements BaseEvent {
  event_type = 'Click-soptmapPromotionWinCTA';

  constructor(public event_properties: ClickSoptmapPromotionWinCtaProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickSoptmapRecommend implements BaseEvent {
  event_type = 'Click-soptmapRecommend';

  constructor(public event_properties: ClickSoptmapRecommendProperties) {
    this.event_properties = event_properties;
  }
}

export class ClickViewMemberModal implements BaseEvent {
  event_type = 'Click-viewMemberModal';

  constructor(public event_properties?: ClickViewMemberModalProperties) {
    this.event_properties = event_properties;
  }
}

export class CompleteSoptmapRegistration implements BaseEvent {
  event_type = 'Complete-soptmapRegistration';

  constructor(public event_properties: CompleteSoptmapRegistrationProperties) {
    this.event_properties = event_properties;
  }
}

export class CompletedCommentPosting implements BaseEvent {
  event_type = 'Completed-commentPosting';

  constructor(public event_properties?: CompletedCommentPostingProperties) {
    this.event_properties = event_properties;
  }
}

export class CompletedFeedPosting implements BaseEvent {
  event_type = 'Completed-feedPosting';

  constructor(public event_properties?: CompletedFeedPostingProperties) {
    this.event_properties = event_properties;
  }
}

export class CompletedFeedPostingCanceled implements BaseEvent {
  event_type = 'Completed-feedPostingCanceled';

  constructor(public event_properties?: CompletedFeedPostingCanceledProperties) {
    this.event_properties = event_properties;
  }
}

export class CompletedMakeGroup implements BaseEvent {
  event_type = 'Completed-makeGroup';

  constructor(public event_properties: CompletedMakeGroupProperties) {
    this.event_properties = event_properties;
  }
}

export class EnterEventMaindetail implements BaseEvent {
  event_type = 'Enter-event-maindetail';
}

export class FilterListOptionManagement implements BaseEvent {
  event_type = 'Filter-listOptionManagement';

  constructor(public event_properties?: FilterListOptionManagementProperties) {
    this.event_properties = event_properties;
  }
}

export class FilterManagementListOrder implements BaseEvent {
  event_type = 'Filter-managementListOrder';

  constructor(public event_properties?: FilterManagementListOrderProperties) {
    this.event_properties = event_properties;
  }
}

export class ImpressionBanner implements BaseEvent {
  event_type = 'Impression-banner';

  constructor(public event_properties?: ImpressionBannerProperties) {
    this.event_properties = event_properties;
  }
}

export class PushEnteredUser implements BaseEvent {
  event_type = 'Push-entered-user';

  constructor(public event_properties?: PushEnteredUserProperties) {
    this.event_properties = event_properties;
  }
}

export class StartGroup implements BaseEvent {
  event_type = 'Start-group';

  constructor(public event_properties: StartGroupProperties) {
    this.event_properties = event_properties;
  }
}

export class ViewSoptmapFirstRegisterPromotion implements BaseEvent {
  event_type = 'View-soptmapFirstRegisterPromotion';

  constructor(public event_properties: ViewSoptmapFirstRegisterPromotionProperties) {
    this.event_properties = event_properties;
  }
}

export class ViewSoptmapTab implements BaseEvent {
  event_type = 'View-soptmapTab';

  constructor(public event_properties?: ViewSoptmapTabProperties) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Apply-multiplefilter
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Apply-multiplefilter)
   *
   * 사용자가 필터 내 하위 항목 선택=모임을 조회
   *
   * @param properties The event's properties (e.g. Applied_generation)
   * @param options Amplitude event options.
   */
  applyMultiplefilter(
    properties?: ApplyMultiplefilterProperties,
    options?: EventOptions,
  ) {
    return this.track(new ApplyMultiplefilter(properties), options);
  }

  /**
   * Apply-soptmapFilter
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Apply-soptmapFilter)
   *
   * 솝맵 내에서 카테고리 필터 적용 시 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. soptmap_category)
   * @param options Amplitude event options.
   */
  applySoptmapFilter(
    properties: ApplySoptmapFilterProperties,
    options?: EventOptions,
  ) {
    return this.track(new ApplySoptmapFilter(properties), options);
  }

  /**
   * Attach-feedPhoto
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Attach-feedPhoto)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. platform_type)
   * @param options Amplitude event options.
   */
  attachFeedPhoto(
    properties?: AttachFeedPhotoProperties,
    options?: EventOptions,
  ) {
    return this.track(new AttachFeedPhoto(properties), options);
  }

  /**
   * Click-banner
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-banner)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. banner_id)
   * @param options Amplitude event options.
   */
  clickBanner(
    properties?: ClickBannerProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickBanner(properties), options);
  }

  /**
   * Click-carouselArrow
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-carouselArrow)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. image_total)
   * @param options Amplitude event options.
   */
  clickCarouselArrow(
    properties?: ClickCarouselArrowProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickCarouselArrow(properties), options);
  }

  /**
   * Click-commentLike
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-commentLike)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickCommentLike(
    properties?: ClickCommentLikeProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickCommentLike(properties), options);
  }

  /**
   * Click-draft-dialog
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-draft-dialog)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. dialog_action)
   * @param options Amplitude event options.
   */
  clickDraftDialog(
    properties: ClickDraftDialogProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickDraftDialog(properties), options);
  }

  /**
   * Click-event-apply
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-event-apply)
   *
   * 유저가 행사 모임 상세 페이지에서 \[신청하기\] 버튼을 클릭할 때 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. Applied_generation)
   * @param options Amplitude event options.
   */
  clickEventApply(
    properties?: ClickEventApplyProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickEventApply(properties), options);
  }

  /**
   * Click-eventbanner-mainCTA
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-eventbanner-mainCTA)
   *
   * 유저가 행사 전용 배너 내 CTA를 클릭해 행사 모임으로 이동을 시도할 때 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. event_id)
   * @param options Amplitude event options.
   */
  clickEventbannerMainCta(
    properties?: ClickEventbannerMainCtaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickEventbannerMainCta(properties), options);
  }

  /**
   * Click-eventbanner-subCTA
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-eventbanner-subCTA)
   *
   * 사용자가 행사 전용 배너의 서브 CTA를 통해 행사 검색 결과가 적용된 전체모임 화면에 진입할 때 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. event_generation_type)
   * @param options Amplitude event options.
   */
  clickEventbannerSubCta(
    properties?: ClickEventbannerSubCtaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickEventbannerSubCta(properties), options);
  }

  /**
   * Click-feedAction
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedAction)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickFeedAction(
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedAction(), options);
  }

  /**
   * Click-feedCard
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedCard)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickFeedCard(
    properties?: ClickFeedCardProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedCard(properties), options);
  }

  /**
   * Click-feedCardGroupLabel
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedCardGroupLabel)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_id)
   * @param options Amplitude event options.
   */
  clickFeedCardGroupLabel(
    properties?: ClickFeedCardGroupLabelProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedCardGroupLabel(properties), options);
  }

  /**
   * Click-feeddetailLike
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feeddetailLike)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickFeeddetailLike(
    properties?: ClickFeeddetailLikeProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeeddetailLike(properties), options);
  }

  /**
   * Click-feeddetatilProfile
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feeddetatilProfile)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickFeeddetatilProfile(
    properties?: ClickFeeddetatilProfileProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeeddetatilProfile(properties), options);
  }

  /**
   * Click-feedlistLike
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedlistLike)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickFeedlistLike(
    properties?: ClickFeedlistLikeProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedlistLike(properties), options);
  }

  /**
   * Click-feedPosting
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedPosting)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_id)
   * @param options Amplitude event options.
   */
  clickFeedPosting(
    properties?: ClickFeedPostingProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedPosting(properties), options);
  }

  /**
   * Click-feedProfile
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedProfile)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickFeedProfile(
    properties?: ClickFeedProfileProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedProfile(properties), options);
  }

  /**
   * Click-feedShard
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-feedShard)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickFeedShard(
    options?: EventOptions,
  ) {
    return this.track(new ClickFeedShard(), options);
  }

  /**
   * Click-filterCategory
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-filterCategory)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_category)
   * @param options Amplitude event options.
   */
  clickFilterCategory(
    properties?: ClickFilterCategoryProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFilterCategory(properties), options);
  }

  /**
   * Click-filterGeneration
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-filterGeneration)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_generation)
   * @param options Amplitude event options.
   */
  clickFilterGeneration(
    properties?: ClickFilterGenerationProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFilterGeneration(properties), options);
  }

  /**
   * Click-filterOn
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-filterOn)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickFilterOn(
    options?: EventOptions,
  ) {
    return this.track(new ClickFilterOn(), options);
  }

  /**
   * Click-filterPart
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-filterPart)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_part)
   * @param options Amplitude event options.
   */
  clickFilterPart(
    properties?: ClickFilterPartProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFilterPart(properties), options);
  }

  /**
   * Click-filterStatus
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-filterStatus)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_status)
   * @param options Amplitude event options.
   */
  clickFilterStatus(
    properties?: ClickFilterStatusProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickFilterStatus(properties), options);
  }

  /**
   * Click-groupCard
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-groupCard)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_category)
   * @param options Amplitude event options.
   */
  clickGroupCard(
    properties?: ClickGroupCardProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickGroupCard(properties), options);
  }

  /**
   * Click-makebymeGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-makebymeGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickMakebymeGroup(
    options?: EventOptions,
  ) {
    return this.track(new ClickMakebymeGroup(), options);
  }

  /**
   * Click-makeGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-makeGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. location)
   * @param options Amplitude event options.
   */
  clickMakeGroup(
    properties?: ClickMakeGroupProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickMakeGroup(properties), options);
  }

  /**
   * Click-manageGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-manageGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickManageGroup(
    options?: EventOptions,
  ) {
    return this.track(new ClickManageGroup(), options);
  }

  /**
   * Click-managementListProfile
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-managementListProfile)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickManagementListProfile(
    options?: EventOptions,
  ) {
    return this.track(new ClickManagementListProfile(), options);
  }

  /**
   * Click-memberManagement
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-memberManagement)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickMemberManagement(
    options?: EventOptions,
  ) {
    return this.track(new ClickMemberManagement(), options);
  }

  /**
   * Click-memberStatus
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-memberStatus)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  clickMemberStatus(
    properties?: ClickMemberStatusProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickMemberStatus(properties), options);
  }

  /**
   * Click-navbarGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-navbarGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. menu)
   * @param options Amplitude event options.
   */
  clickNavbarGroup(
    properties?: ClickNavbarGroupProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickNavbarGroup(properties), options);
  }

  /**
   * Click-noticeOff
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-noticeOff)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickNoticeOff(
    options?: EventOptions,
  ) {
    return this.track(new ClickNoticeOff(), options);
  }

  /**
   * Click-noticeOn
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-noticeOn)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickNoticeOn(
    options?: EventOptions,
  ) {
    return this.track(new ClickNoticeOn(), options);
  }

  /**
   * Click-ownerProfile
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-ownerProfile)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. group_owner_id)
   * @param options Amplitude event options.
   */
  clickOwnerProfile(
    properties?: ClickOwnerProfileProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickOwnerProfile(properties), options);
  }

  /**
   * Click-paginationArrow
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-paginationArrow)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. page)
   * @param options Amplitude event options.
   */
  clickPaginationArrow(
    properties?: ClickPaginationArrowProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickPaginationArrow(properties), options);
  }

  /**
   * Click-paginationNumber
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-paginationNumber)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. page)
   * @param options Amplitude event options.
   */
  clickPaginationNumber(
    properties?: ClickPaginationNumberProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickPaginationNumber(properties), options);
  }

  /**
   * Click-registeredGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-registeredGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  clickRegisteredGroup(
    options?: EventOptions,
  ) {
    return this.track(new ClickRegisteredGroup(), options);
  }

  /**
   * Click-registerGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-registerGroup)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. entry_source)
   * @param options Amplitude event options.
   */
  clickRegisterGroup(
    properties?: ClickRegisterGroupProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickRegisterGroup(properties), options);
  }

  /**
   * Click-soptmapPromotionCheckGift
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-soptmapPromotionCheckGift)
   *
   * **첫 장소 등록 이벤트 프로모션 화면에서 유저가 \[선물 확인하기\] 버튼을 클릭했을 때 발생하는 이벤트**
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  clickSoptmapPromotionCheckGift(
    properties: ClickSoptmapPromotionCheckGiftProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickSoptmapPromotionCheckGift(properties), options);
  }

  /**
   * Click-soptmapPromotionLoseConfirm
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-soptmapPromotionLoseConfirm)
   *
   * **이벤트 프로모션 결과가 ‘꽝’인 화면에서 유저가 \[확인\] 버튼을 클릭했을 때 발생하는 이벤트**
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  clickSoptmapPromotionLoseConfirm(
    properties: ClickSoptmapPromotionLoseConfirmProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickSoptmapPromotionLoseConfirm(properties), options);
  }

  /**
   * Click-soptmapPromotionWinCTA
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-soptmapPromotionWinCTA)
   *
   * **이벤트 프로모션 결과가 ‘당첨’인 화면에서 유저가 \[선물 받으러 가기\] 버튼을 클릭했을 때 발생하는 이벤트**
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  clickSoptmapPromotionWinCta(
    properties: ClickSoptmapPromotionWinCtaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickSoptmapPromotionWinCta(properties), options);
  }

  /**
   * Click-soptmapRecommend
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-soptmapRecommend)
   *
   * 솝맵 내, 장소 목록에서 '나도 추천해요' 버튼 클릭 시 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  clickSoptmapRecommend(
    properties: ClickSoptmapRecommendProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickSoptmapRecommend(properties), options);
  }

  /**
   * Click-viewMemberModal
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Click-viewMemberModal)
   *
   * 모임 상세 페이지에서 사용자가 (기수or파트) 참여 멤버 확인 CTA를 클릭했을 때 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. Applied_generation)
   * @param options Amplitude event options.
   */
  clickViewMemberModal(
    properties?: ClickViewMemberModalProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickViewMemberModal(properties), options);
  }

  /**
   * Complete-soptmapRegistration
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Complete-soptmapRegistration)
   *
   * 솝맵 내, ‘장소 등록하기’ 페이지에서 등록 완료 시 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  completeSoptmapRegistration(
    properties: CompleteSoptmapRegistrationProperties,
    options?: EventOptions,
  ) {
    return this.track(new CompleteSoptmapRegistration(properties), options);
  }

  /**
   * Completed-commentPosting
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Completed-commentPosting)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. crew_status)
   * @param options Amplitude event options.
   */
  completedCommentPosting(
    properties?: CompletedCommentPostingProperties,
    options?: EventOptions,
  ) {
    return this.track(new CompletedCommentPosting(properties), options);
  }

  /**
   * Completed-feedPosting
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Completed-feedPosting)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. feed_upload)
   * @param options Amplitude event options.
   */
  completedFeedPosting(
    properties?: CompletedFeedPostingProperties,
    options?: EventOptions,
  ) {
    return this.track(new CompletedFeedPosting(properties), options);
  }

  /**
   * Completed-feedPostingCanceled
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Completed-feedPostingCanceled)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. location)
   * @param options Amplitude event options.
   */
  completedFeedPostingCanceled(
    properties?: CompletedFeedPostingCanceledProperties,
    options?: EventOptions,
  ) {
    return this.track(new CompletedFeedPostingCanceled(properties), options);
  }

  /**
   * Completed-makeGroup
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Completed-makeGroup)
   *
   * 모임 생성을 완료했을 경우
   *
   * @param properties The event's properties (e.g. from_resume)
   * @param options Amplitude event options.
   */
  completedMakeGroup(
    properties: CompletedMakeGroupProperties,
    options?: EventOptions,
  ) {
    return this.track(new CompletedMakeGroup(properties), options);
  }

  /**
   * Enter-event-maindetail
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Enter-event-maindetail)
   *
   * 사용자가 행사 전용 배너의 메인 CTA(내 파트 신청하기)를 통해 본인 파트에 해당하는 행사 모임 상세 페이지에 진입할 때 발생하는 이벤트
   *
   * @param options Amplitude event options.
   */
  enterEventMaindetail(
    options?: EventOptions,
  ) {
    return this.track(new EnterEventMaindetail(), options);
  }

  /**
   * Filter-listOptionManagement
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Filter-listOptionManagement)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. manage_listing_no)
   * @param options Amplitude event options.
   */
  filterListOptionManagement(
    properties?: FilterListOptionManagementProperties,
    options?: EventOptions,
  ) {
    return this.track(new FilterListOptionManagement(properties), options);
  }

  /**
   * Filter-managementListOrder
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Filter-managementListOrder)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. manage_sort)
   * @param options Amplitude event options.
   */
  filterManagementListOrder(
    properties?: FilterManagementListOrderProperties,
    options?: EventOptions,
  ) {
    return this.track(new FilterManagementListOrder(properties), options);
  }

  /**
   * Impression-banner
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Impression-banner)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. banner_id)
   * @param options Amplitude event options.
   */
  impressionBanner(
    properties?: ImpressionBannerProperties,
    options?: EventOptions,
  ) {
    return this.track(new ImpressionBanner(properties), options);
  }

  /**
   * Push-entered-user
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Push-entered-user)
   *
   * 모임 푸시 알림으로 상세 페이지 진입
   *
   * @param properties The event's properties (e.g. user_id)
   * @param options Amplitude event options.
   */
  pushEnteredUser(
    properties?: PushEnteredUserProperties,
    options?: EventOptions,
  ) {
    return this.track(new PushEnteredUser(properties), options);
  }

  /**
   * Start-group
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/Start-group)
   *
   * 헤더에서 \[모임\] 메뉴 버튼 클릭했을 때 수집되는 이벤트
   *
   * @param properties The event's properties (e.g. screen_width)
   * @param options Amplitude event options.
   */
  startGroup(
    properties: StartGroupProperties,
    options?: EventOptions,
  ) {
    return this.track(new StartGroup(properties), options);
  }

  /**
   * View-soptmapFirstRegisterPromotion
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/View-soptmapFirstRegisterPromotion)
   *
   * 유저가 장소를 최초 등록한 이후, 첫 등록 기념 이벤트 프로모션 화면에 진입했을 때 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. place_id)
   * @param options Amplitude event options.
   */
  viewSoptmapFirstRegisterPromotion(
    properties: ViewSoptmapFirstRegisterPromotionProperties,
    options?: EventOptions,
  ) {
    return this.track(new ViewSoptmapFirstRegisterPromotion(properties), options);
  }

  /**
   * View-soptmapTab
   *
   * [View in Tracking Plan](https://data.amplitude.com/sopt-makers/sopt-makers-crew-prd/events/main/latest/View-soptmapTab)
   *
   * 사용자가 '솝맵' 탭에 진입 시 발생하는 이벤트
   *
   * @param properties The event's properties (e.g. user_id)
   * @param options Amplitude event options.
   */
  viewSoptmapTab(
    properties?: ViewSoptmapTabProperties,
    options?: EventOptions,
  ) {
    return this.track(new ViewSoptmapTab(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
