name: Playground - Build App

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: false
        type: string
        default: ''
      env:
        required: true
        type: string
      upload:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout_ref || github.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.1.1 --activate
          yarn -v

      - name: Cache Yarn
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install --immutable

      - name: Nextjs Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/playground/.next/cache
          key: ${{ runner.os }}-playground-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('apps/playground/**/*.[jt]s', 'apps/playground/**/*.[jt]sx', 'apps/playground/next.config.js', 'apps/playground/package.json', 'packages/**/*.[jt]s', 'packages/**/*.[jt]sx', 'packages/**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-playground-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Set .env
        run: |
          cp apps/playground/.env.development apps/playground/.env.local
          echo "${{ inputs.env }}" > apps/playground/.env.local

      - name: Build
        run: yarn build:playground

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r apps/playground/out/* deploy/
          cp -r apps/playground/functions deploy/

      - uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: deploy
          if-no-files-found: error
          retention-days: 7
