name: Check

on:
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.1.1 --activate
          yarn -v

      - name: Cache Yarn
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install --immutable

      - name: Check All
        run: |
          set -o pipefail
          yarn check | tee check.log

      - name: Print Summary
        if: always()
        run: |
          echo "## Check Result" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat check.log)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
