name: Crew - Production Deploy

on:
  workflow_dispatch:
    inputs:
      release_sha:
        description: 'Production에 배포할 Git 커밋 SHA'
        required: true
        type: string

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release_sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.1.1 --activate
          yarn -v

      - name: Cache Yarn
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install --immutable

      - name: Cache Crew Next.js build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/crew/.next/cache
          key: ${{ runner.os }}-crew-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('apps/crew/**/*.[jt]s', 'apps/crew/**/*.[jt]sx', 'apps/crew/next.config.js', 'apps/crew/package.json', 'packages/**/*.[jt]s', 'packages/**/*.[jt]sx', 'packages/**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-crew-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Set .env
        run: |
          echo "${{ secrets.PROJECT_ENV }}" > apps/crew/.env.local
          echo "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}" >> apps/crew/.env.local
          echo "NEXT_PUBLIC_KAKAO_TALK_PLUGIN_KEY=${{ vars.NEXT_PUBLIC_KAKAO_TALK_PLUGIN_KEY }}" >> apps/crew/.env.local
          echo "NEXT_PUBLIC_SENTRY_DSN=${{ vars.NEXT_PUBLIC_SENTRY_DSN }}" >> apps/crew/.env.local
          echo "NEXT_PUBLIC_AMPLITUDE_API_KEY=${{ vars.NEXT_PUBLIC_AMPLITUDE_API_KEY }}" >> apps/crew/.env.local
          echo "NEXT_PUBLIC_APP_ENV=${{ vars.NEXT_PUBLIC_APP_ENV }}" >> apps/crew/.env
          echo "NEXT_PUBLIC_OPERATION_API_URL=${{ vars.NEXT_PUBLIC_OPERATION_API_URL }}" >> apps/crew/.env.local
          echo "NEXT_PUBLIC_ADMIN_KEY=${{ secrets.NEXT_PUBLIC_ADMIN_KEY }}" >> apps/crew/.env.local

      - name: Build
        run: yarn build:crew

      - name: Move artifacts into dist folder
        run: cd apps/crew && mkdir group && mv out/* group/ && mv group out

      - name: Deploy
        run: yarn run wrangler pages deploy "apps/crew/out" --project-name "${{ secrets.CLOUDFLARE_PAGES_CREW_PROJECT_NAME }}" --commit-message "${{ inputs.release_sha }}" --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
